# Generated by Django 4.1.7 on 2023-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('limit', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
